DROP TABLE IF EXISTS t013_queues;
DROP TABLE IF EXISTS t012_test;
DROP TABLE IF EXISTS t011_messages_error;
DROP TABLE IF EXISTS t010_log_app;
DROP TABLE IF EXISTS t009_details;
DROP TABLE IF EXISTS t008_orders;
DROP TABLE IF EXISTS t007_messages;
DROP TABLE IF EXISTS t006_companies;
DROP TABLE IF EXISTS t005_services;
DROP TABLE IF EXISTS t004_locations;
DROP TABLE IF EXISTS t003_patients;
DROP TABLE IF EXISTS t002_types_documents;
DROP TABLE IF EXISTS t001_users;

CREATE TABLE IF NOT EXISTS t001_users(
    f001_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    f001_username  VARCHAR(20) NOT NULL UNIQUE,
    f001_password  VARCHAR(20) NOT NULL,
    f001_active    BOOLEAN DEFAULT FALSE,
    f001_delete    BOOLEAN DEFAULT FALSE,
    f001_create_at DATETIME default (datetime('now', 'localtime'))
);

INSERT INTO t001_users (f001_username, f001_password, f001_active)
VALUES ('admin', 'admin', true);

CREATE TABLE t002_types_documents(
    f002_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    f002_code      VARCHAR(10 ) NOT NULL UNIQUE,
    f002_name      VARCHAR(250) NOT NULL,
    f002_active    BOOLEAN  DEFAULT FALSE,
    f002_delete    BOOLEAN  DEFAULT FALSE,
    f002_create_at DATETIME DEFAULT (datetime('now', 'localtime')),
    f002_f001_id   INTEGER  DEFAULT 1,
    FOREIGN KEY (f002_f001_id)
        REFERENCES t001_users (f001_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

INSERT INTO t002_types_documents (f002_code, f002_name, f002_active)
VALUES ('NA', 'NO APLICA', TRUE);

CREATE TABLE IF NOT EXISTS t003_patients (
    f003_id              INTEGER PRIMARY KEY AUTOINCREMENT,
    f003_f002_id         INTEGER NOT NULL,
    f003_number          VARCHAR(25 ) NOT NULL,
    f003_first_name      VARCHAR(50 ) NOT NULL,
    f003_second_name     VARCHAR(50 ) DEFAULT NULL,
    f003_last_name       VARCHAR(50 ) NOT NULL,
    f003_middle_name     VARCHAR(50 ) DEFAULT NULL,
    f003_birth_date      DATE DEFAULT NULL,
    f003_gender          VARCHAR(1) DEFAULT NULL,
    f003_expedition_date DATE DEFAULT NULL,
    f003_blood_type      VARCHAR(10 ) DEFAULT NULL,
    f003_address         VARCHAR(250) DEFAULT NULL,
    f003_phone           VARCHAR(50 ) DEFAULT NULL,
    f003_cell_phone      VARCHAR(50 ) DEFAULT NULL,
    f003_email           VARCHAR(250) DEFAULT NULL,
    f003_create_at       DATETIME DEFAULT (datetime('now', 'localtime')),
    f003_update_at       DATETIME DEFAULT (datetime('now', 'localtime')),
    f003_active          BOOLEAN DEFAULT FALSE,
    f003_delete          BOOLEAN DEFAULT FALSE,
    f003_f001_id         INTEGER NOT NULL,
    FOREIGN KEY (f003_f002_id)
        REFERENCES t002_types_documents (f002_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    FOREIGN KEY (f003_f001_id)
        REFERENCES t001_users (f001_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS t004_locations(
    f004_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    f004_create_at DATETIME DEFAULT (datetime('now', 'localtime')),
    f004_code      VARCHAR(50 ) NOT NULL UNIQUE,
    f004_name      VARCHAR(250) NOT NULL,
    f004_active    BOOLEAN DEFAULT FALSE,
    f004_delete    BOOLEAN DEFAULT FALSE,
    f004_f001_id   INTEGER DEFAULT 1,
    FOREIGN KEY (f004_f001_id)
        REFERENCES t001_users (f001_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

INSERT INTO t004_locations (f004_code, f004_name, f004_active)
VALUES
('CEXT', 'CONSULTA EXTERNA', TRUE),
('CIRA', 'CIRUGIA AMBULATORIA', TRUE),
('DT05', 'LABORATORIO CLINICO', TRUE),
('DT11', 'SALA DE TRABAJO DE PARTO', TRUE),
('FEXT', 'FIBROSIS CONSULTA EXTERNA', TRUE),
('GO01', 'RECUPERACION OBSTETRICIA', TRUE),
('HOS2', 'HOSPITALIZACION PISO 2', TRUE),
('HOS3', 'HOSPITALIZACION PISO 3', TRUE),
('HOS4', 'HOSPITALIZACION PISO 4', TRUE),
('HOS5', 'HOSPITALIZACION PISO 5', TRUE),
('ONCO', 'ONCOLOGIA', TRUE),
('OU'  , 'URGENCIAS OBSTETRICIA', TRUE),
('PD01', 'CONSULTORIO PEDIATRICA', TRUE),
('PD14', 'PEDIATRIA', TRUE),
('RADI', 'RADIOLOGIA', TRUE),
('RQX2', 'RECUPERACION CIRUGIA 2 PISO', TRUE),
('RQX4', 'RECUPERACION CIRUGIA 4 PISO', TRUE),
('SA05', 'HEMODINAMIA', TRUE),
('UADG', 'U DE ALTA DEPENDENCIA GINECO', TRUE),
('UC01', 'UNIDAD CUIDADO BASICO NEONATAL', TRUE),
('UC02', 'UCI ADULTOS', TRUE),
('UC03', 'UCI NEONATOS', TRUE),
('UC04', 'UCI PEDIATRICA', TRUE),
('UC06', 'UNIDAD CUIDADO INTERM. NEONATO', TRUE),
('UQX2', 'UNIDAD QUIRURGICA 2 PISO', TRUE),
('UQX4', 'UNIDAD QUIRURGICA 4 PISO', TRUE),
('UR03', 'SALA DE REANIMACION PEDIATRICA', TRUE),
('UR06', 'CONSULTORIO ADULTOS', TRUE),
('UR07', 'SALA DE REANIMACION ADULTOS', TRUE),
('UR09', 'OBSERVACION PEDIATRIA', TRUE),
('UR10', 'OBSERVACION ADULTOS', TRUE),
('UR12', 'SALA DE TRAUMA', TRUE);

CREATE TABLE IF NOT EXISTS t005_services(
    f005_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    f005_create_at DATETIME DEFAULT (datetime('now', 'localtime')),
    f005_code      VARCHAR(50 ) NOT NULL UNIQUE,
    f005_name      VARCHAR(250) NOT NULL,
    f005_active    BOOLEAN DEFAULT FALSE,
    f005_delete    BOOLEAN DEFAULT FALSE,
    f005_f001_id   INTEGER DEFAULT 1,
    FOREIGN KEY (f005_f001_id)
        REFERENCES t001_users (f001_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

INSERT INTO t005_services (f005_code, f005_name, f005_active)
VALUES
('NA', 'NO APLICA', TRUE),
('23', 'HEMODINAMIA', TRUE),
('24', 'RADIOLOGIA', TRUE),
('27', 'LABORATORIO CLINICO ESPECIALIZ', TRUE),
('40', 'OBSTETRICIA', TRUE),
('44', 'PEDIATRIA', TRUE),
('57', 'UCI NEONATAL', TRUE),
('58', 'UCI PEDIATRICA', TRUE),
('60', 'UNIDAD CUIDADO INTERMEDIO NEON', TRUE),
('61', 'URGENCIAS', TRUE),
('68', 'CONSULTA EXTERNA', TRUE),
('69', 'HOSPITALIZACION PISO 4', TRUE),
('71', 'HOSPITALIZACION PISO 3', TRUE),
('72', 'UNIDAD DE CUIDADO CRITICO', TRUE),
('77', 'ONCOLOGIA', TRUE),
('81', 'HOSPITALIZACION PISO 2', TRUE),
('83', 'CIRUGIA AMBULATORIA', TRUE),
('85', 'HOSPITALIZACION PISO 5', TRUE),
('87', 'UN. ALTA DEPENDENCIA GINECO', TRUE),
('91', 'FIBROSIS CONSULTA EXTERNA', TRUE);

CREATE TABLE IF NOT EXISTS t006_companies (
    f006_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    f006_create_at DATETIME DEFAULT (datetime('now', 'localtime')),
    f006_code      VARCHAR(50 ) NOT NULL UNIQUE,
    f006_name      VARCHAR(50 ) NOT NULL,
    f006_active    BOOLEAN DEFAULT FALSE,
    f006_delete    BOOLEAN DEFAULT FALSE,
    f006_f001_id   INTEGER DEFAULT 1,
    FOREIGN KEY (f006_f001_id)
        REFERENCES t001_users (f001_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS t007_messages (
    f007_id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    f007_create_at          DATETIME     DEFAULT (datetime('now', 'localtime')),
    f007_create_by          VARCHAR(50 ) DEFAULT '__system__',
    f007_sender             VARCHAR(50 ) DEFAULT NULL,
    f007_sender_facility    VARCHAR(50 ) DEFAULT NULL,
    f007_reception          VARCHAR(50 ) DEFAULT NULL,
    f007_reception_facility VARCHAR(50 ) DEFAULT NULL,
    f007_control_id         VARCHAR(250) NOT NULL,
    f007_content            TEXT        DEFAULT NULL,
    f007_response           TEXT        DEFAULT NULL,
    f007_type_message       VARCHAR(50) DEFAULT NULL, -- ORM^O01 | ORU^O01
    f007_delete             BOOLEAN  DEFAULT FALSE,
    f007_indicted_at        DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS t008_orders (
    f008_id             INTEGER         PRIMARY KEY AUTOINCREMENT,
    f008_number         VARCHAR(50)     NOT NULL,           -- numero de orden
    f008_date           DATE            NOT NULL,           -- fecha de la orden
    f008_time           TIME            NOT NULL,           -- hora de la order
    f008_f007_id        INTEGER         NOT NULL,           -- id del mensaje
    f008_f003_id        INTEGER         NOT NULL,           -- id del paciente
    f008_f004_id        INTEGER         NOT NULL,           -- id de la ubicación
    f008_f005_id        INTEGER         NOT NULL,           -- id del servicio
    f008_f006_id        INTEGER         NOT NULL,           -- id de la empresa
    f008_priority       INTEGER         DEFAULT 0,          -- prioridad de la orden segun el primer examen
    f008_bed            VARCHAR(50 )    DEFAULT NULL,       -- codigo de cama
    f008_type_service   VARCHAR(1  ),                       -- E: empresa | P: Particular
    f008_entity         VARCHAR(500),                       -- tipo de entidad
    f008_history        VARCHAR(50 ),                       -- número de historia clinica
    f008_service        VARCHAR(50 )    DEFAULT NULL,
    f008_create_at      DATETIME        DEFAULT (datetime('now', 'localtime')),
    FOREIGN KEY (f008_f007_id)
        REFERENCES t007_messages (f007_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    FOREIGN KEY (f008_f003_id)
        REFERENCES t003_patients
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    FOREIGN KEY (f008_f004_id)
        REFERENCES t004_locations(f004_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    FOREIGN KEY (f008_f005_id)
        REFERENCES t005_services (f005_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    FOREIGN KEY (f008_f006_id)
        REFERENCES t006_companies (f006_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS t009_details (
    f009_id             INTEGER      PRIMARY KEY AUTOINCREMENT,
    f009_create_at      DATETIME     DEFAULT (datetime('now', 'localtime')),
    f009_f008_id        INTEGER      NOT NULL,
    f009_barcode        VARCHAR(50 ) NOT NULL,
    f009_sequence       INTEGER      NOT NULL,
    f009_test           VARCHAR(20 ) NOT NULL,
    f009_name           VARCHAR(250) NOT NULL,
    f009_date_test      DATETIME     DEFAULT NULL,
    f009_indicted       BOOLEAN      DEFAULT FALSE,
    f009_indicted_at    DATETIME     DEFAULT NULL,
    FOREIGN KEY (f009_f008_id)
        REFERENCES t008_orders (f008_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS t010_log_app(
    f010_id INTEGER PRIMARY KEY AUTOINCREMENT,
    f010_create_at  DATETIME DEFAULT (datetime('now', 'localtime')),
    f010_user       VARCHAR(20) DEFAULT '__system__',
    f010_content    TEXT DEFAULT NULL,
    f010_notify     BOOLEAN DEFAULT FALSE,
    f010_show       BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS t011_messages_error (
    f011_id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    f011_create_at          DATETIME        DEFAULT (datetime('now', 'localtime')),
    f011_create_by          VARCHAR(50 )    DEFAULT '__system__',
    f011_sender             VARCHAR(50 )    DEFAULT NULL,
    f011_sender_facility    VARCHAR(50 )    DEFAULT NULL,
    f011_reception          VARCHAR(50 )    DEFAULT NULL,
    f011_reception_facility VARCHAR(50 )    DEFAULT NULL,
    f011_control_id         VARCHAR(250)    NOT NULL,
    f011_content            TEXT            DEFAULT NULL,
    f011_response           TEXT            DEFAULT NULL,
    f011_type_message       VARCHAR(50)     DEFAULT NULL, -- ORM^O01 | ORU^O01
    f011_delete             BOOLEAN         DEFAULT FALSE,
    f011_indicted_at        DATETIME        DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS t012_test(
    f012_id         INTEGER         PRIMARY KEY AUTOINCREMENT,
    f012_create_at  DATETIME        DEFAULT (datetime('now', 'localtime')),
    f012_code       VARCHAR(20 )    NOT NULL UNIQUE,
    f012_name       VARCHAR(250)    DEFAULT NULL,
    f012_active     BOOLEAN         DEFAULT FALSE,
    f012_group_by   INT             DEFAULT 0
);

INSERT INTO t012_test ( f012_code, f012_name, f012_active, f012_group_by)
VALUES
('999'   , 'NO PROCESS', True, 0),
('903895', 'CREATININA EN SUERO U OTROS FLUIDOS', True, 0),
('904508', 'GONADOTROPINA CORIONICA, SUBUNIDAD BETA CUALITATIVA, (BHCG)', True, 0),
('903856', 'NITROGENO UREICO (BUN)', True, 0),
('902210', 'HEMOGRAMA IV (HEMOGLOBINA- HEMATOCRITO- RECUENTO DE ERITROCI', True, 0),
('901107', 'COLORACION GRAM Y LECTURA PARA CUALQUIER MUESTRA', True, 0),
('907106', 'UROANALISIS', True, 0),
('903813', 'CLORO (CLORURO)', True, 0),
('903864', 'SODIO', True, 0),
('902045', 'TIEMPO DE PROTROMBINA (PT)', True, 0),
('902049', 'TIEMPO DE TROMBOPLASTINA PARCIAL (PTT)', True, 0),
('903841', 'GLUCOSA EN SUERO, LCR U OTRO FLUIDO DIFERENTE A ORINA', True, 0),
('903859', 'POTASIO', True, 0),
('906913', 'PROTEINA C REACTIVA, CUANTITATIVO DE ALTA PRECISION', True, 0),
('903833', 'FOSFATASA ALCALINA', True, 0),
('903805', 'AMILASA', True, 0),
('903866', 'TRANSAMINASA GLUTAMICO PIRUVICA O ALANINO AMINO TRANSFERASA', True, 0),
('903854', 'MAGNESIO', True, 0),
('903604', 'CALCIO IONICO', True, 0),
('903867', 'TRANSAMINASA GLUTAMICO OXALACETICA O ASPARTATO AMINO TRANSFE', True, 0),
('903809', 'BILIRRUBINAS TOTAL Y DIRECTA', True, 0),
('903824', 'CREATININA EN ORINA DE 24 H', True, 0),
('903862', 'PROTEINAS EN ORINA DE 24 H', True, 0),
('903811', 'CALCIO EN ORINA DE 24 H POR COLORIMETRIA', True, 0),
('904903', 'HORMONA ESTIMULANTE DEL TIROIDES (TSH) NEONATAL', True, 0),
('903860', 'POTASIO EN ORINA DE 24 H *', True, 0),
('903426', 'HEMOGLOBINA GLICOSILADA POR ANTICUERPOS MONOCLONALES', True, 0),
('903437', 'TROPONINA I, CUANTITATIVA', True, 0),
('906040', 'TREPONEMA PALLIDUM- ANTICUERPOS IG G', True, 0),
('906249', 'VIH 1 Y 2, ANTICUERPOS', True, 0),
('906129', 'TOXOPLASMA GONDI-ANTICUERPOS IG M', True, 0),
('903828', 'DESHIDROGENASA LACTICA (LDH)', True, 0),
('902104', 'DIMERO D POR EIA', True, 0),
('903016', 'FERRITINA', True, 0),
('903835', 'FOSFORO INORGANICO (FOSFATOS)', True, 0),
('901221', 'HEMOCULTIVO AEROBIO POR METODO AUTOMATICO', True, 0),
('901217', 'CULTIVO PARA MICROORGANISMOS EN CUALQUIER MUESTRA DIFERENTE', True, 0),
('903810', 'CALCIO POR COLORIMETRIA', True, 0),
('901236', 'UROCULTIVO (ANTIBIOGRAMA MIC AUTOMATICO)', True, 0),
('906340', 'SARS COV 2 [COVID-19] ANTIGENO', True, 1),
('908856', 'IDENTIFICACION DE OTRO VIRUS (ESPECIFICA) POR PRUEBAS MOLECULAR', True, 1),
('903868', 'TRIGLICERIDOS', True, 0),
('903818', 'COLESTEROL TOTAL', True, 0),
('906625', 'GONADOTROPINA CORIONICA, SUBUNIDAD BETA CUANTITATIVA (BHCG)', True, 0),
('906301', 'ADENOVIRUS ANTIGENO', True, 0),
('906329', 'VIRUS SICITIAL RESPIRATORIO, ANTIGENO', True, 0),
('906321', 'INFLUENZA, ANTIGENO', True, 0),
('903839', 'GASES ARTERIALES Y/ O VENOSOS (EN REPOSO O EN EJERCICIO)', True, 0),
('902223', 'RECUENTO DE RETICULOCITOS- METODO MANUAL', True, 0),
('902206', 'EXTENDIDO DE SANGRE PERIFERICA- ESTUDIO DE MORFOLOGIA', True, 0),
('911009', 'COOMBS DIRECTO, CUALITATIVO POR MICROTECNICA', True, 0),
('901101', 'COLORACION ACIDO ALCOHOL RESISTENTE (ZIELH-NEELSEN) BK', True, 0),
('903803', 'ALBUMINA EN SANGRE', True, 0),
('903111', 'ACIDO LACTICO (L-LACTATO) POR METODO ENZIMATICO', True, 0),
('902204', 'ERITROSEDIMENTACION (VELOCIDAD SEDIMENTACION GLOBULAR) VSG', True, 0),
('907004', 'COPROSCOPICO', True, 0),
('901223', 'HEMOCULTIVO ANAEROBIO POR METODO AUTOMATICO', True, 0),
('903816', 'COLESTEROL DE BAJA DENSIDAD [LDL] E', True, 0),
('903815', 'COLESTEROL DE ALTA DENSIDAD (HDL)', True, 0),
('906610', 'ANTIGENO ESPECIFICO DE PROSTATA (PSA)', True, 0),
('903044', 'SATURACION DE TRANSFERRINA', True, 0),
('903045', 'TRANSFERRINA POR IDR', True, 0),
('903846', 'HIERRO SERICO', True, 0),
('906317', 'ANTIGENO DE SUPERFICIE (HBSAG)', True, 0),
('906127', 'TOXOPLASMA GONDII- ANTICUERPOS IG G POR EIA', True, 0),
('903602', 'AMONIO', True, 0),
('906225', 'HEPATITIS C, ANTICUERPO (ANTI-HVC)', True, 0),
('906915', 'SEROLOGIA (PRUEBA NO TREPONEMICA) RPR', True, 0),
('906218', 'HEPATITIS A, ANTICUERPOS IG M (ANTI HVA-M) *', True, 0),
('906907', 'COMPLEMENTO SERICO C4 CUANTITATIVO', True, 0),
('906905', 'COMPLEMENTO SERICO C3 CUANTITATIVO', True, 0),
('906219', 'HEPATITIS A, ANTICUERPOS TOTALES (ANTI HVA)', True, 0),
('905726', 'COCAINA, SEMICUANTITATIVA POR INMUNOENSAYO O CROMATOGRAFIA D', True, 0),
('903821', 'CREATIN QUINASA TOTAL CK- CPK', True, 0),
('905717', 'CANNABINOIDES, SEMICUANTITATIVA POR CROMATOGRAFIA DE CAPA FI', True, 0),
('906714', 'LINFOCITOS T CD4 POR CITOMETRIA DE FLUJO', True, 0),
('908832', 'VIRUS DE INMUNODEFICIENCIA HUMANA CARGA VIRAL', True, 0),
('908805', 'CITOMEGALOVIRUS CARGA VIRAL', True, 0),
('904902', 'HORMONA ESTIMULANTE DEL TIROIDES (TSH)', True, 0),
('906841', 'PROCALCITONINA SEMIAUTOMATIZADO O AUTOMATIZADO', True, 0),
('906270', 'SARS COV2 [COVID19] ANTICUERPOS IGG', True, 1),
('906271', 'SARS COV2 [COVID-19] ANTICUERPOS IGM', True, 0),
('905204', 'BARBITURICOS, SEMICUANTITATIVO POR INMUNOENSAYO', True, 0),
('905740', 'OPIACEOS, SEMICUANTITATIVO POR CROMATOGRAFIA', True, 0),
('903801', 'ACIDO URICO', True, 0),
('904921', 'TIROXINA LIBRE', True, 0),
('903863', 'PROTEINAS TOTALES', True, 0),
('906205', 'CITOMEGALOVIRUS- ANTICUERPOS IG G (CMV-G) POR EIA', True, 0),
('906212', 'EPSTEIN-BARR, ANTICUERPOS IG G (CAPSULA EB-VCA-G) POR EIA', True, 0),
('906215', 'EPSTEIN-BARR, ANTICUERPOS IG M (CAPSULA EB-VCA-M) POR EIA', True, 0),
('906206', 'CITOMEGALOVIRUS- ANTICUERPOS IG M (CMV-M) POR EIA', True, 0),
('905410', 'VANCOMICINA AUTOMATIZADO', True, 0),
('903703', 'VITAMINA B 12', True, 0),
('903105', 'ACIDO FOLICO (FOLATOS) EN SUERO', True, 0),
('903876', 'CREATININA EN ORINA PARCIAL', True, 0),
('905306', 'BENZODIACEPINAS, SEMICUANTITATIVA POR CROMATOGRAFIA DE CAPA', True, 0),
('903817', 'COLESTEROL DE BAJA DENSIDAD (LDL) INMUNOLOGICO DIRECTO', True, 0),
('902048', 'TIEMPO DE TROMBINA', True, 0),
('902211', 'HEMATOCRITO HEMOGLOBINA', True, 0),
('902221', 'RECUENTO DE PLAQUETAS- METODO MANUAL', True, 0),
('905302', 'ANFETAMINAS Y METANFETAMINAS, SEMICUANTITATIVA POR INMUNOENS', True, 0),
('904601', 'TESTOSTERONA LIBRE', True, 0),
('905738', 'MONOXIDO DE CARBONO (CARBOXIHEMOGLOBINA) SEMICUANTITATIVO', True, 0),
('905304', 'ANTIDEPRESIVOS TRICICLICOS, SEMICUANTITATIVO POR INMUNOENSAY', True, 0),
('905310', 'FENOTIAZINAS EN SUERO, ORINA Y LAVADO GASTRICO, SEMICUANTITA', True, 0),
('905711', 'ATROPINICOS, SEMICUANTITATIVO POR CROMATOGRAFIA DE CAPA FINA', True, 0),
('904004', 'RENINA TOTAL', True, 0),
('904912', 'HORMONA PARATIROIDEA MOLECULA INTACTA', True, 0),
('906843', 'INMUNOGLOBULINAS CADENAS LIVIANAS LIBRES LAMBDA SEMIAUTOMATI', True, 0),
('906842', 'INMUNOGLOBULINAS CADENAS LIVIANAS LIBRES KAPPA SEMIAUTOMATIZ', True, 0),
('906001', 'ANTIESTREPTOLISINA', True, 0),
('902024', 'FIBRINOGENO', True, 0),
('903837', 'FRACCION EXCRETADA DE SODIO (FENA)', True, 0),
('905759', 'SUSTANCIAS ALUCINOGENAS', True, 0),
('903819', 'CREATIN QUINASA (FRACCION MB) POR ESPECTOFOTOMETRIA', True, 0),
('906131', 'TRIPANOZOMA CRUZY( CHAGAS) ANTICUERPOS POR EIA', True, 0),
('907008', 'SANGRE OCULTA EN MATERIA FECAL (GUAYACO O EQUIVALENTE)', True, 0),
('906910', 'FACTOR REMATOIDEO (R.A.) CUANTITATIVO POR NEFELOMETRIA', True, 0),
('906454', 'RO/SSA, ANTICUERPOS POR EIA', True, 0),
('906406', 'ANTICUERPOS EXTRACTABLES TOTALES (ENAS) SS-A (RO) SS-B (LA)', True, 0),
('906437', 'MUSCULO LISO, ANTICUERPOS (ASMA) POR IFI', True, 0),
('906441', 'NUCLEARES, ANTICUERPOS (ANA) POR IFI', True, 0),
('906453', 'RNP, ANTICUERPOS', True, 0),
('907002', 'COPROLOGICO', True, 0),
('901209', 'CULTIVO DE LIQUIDOS CORPORALES: BILIS- L.C.R- PERITONEAL- PL', True, 0),
('903827', 'CUERPOS CETONICOS O CETONAS EN SANGRE (114)', True, 0),
('903706', 'VITAMINA D 25 DIHIDROXI', True, 0),
('901218', 'CULTIVO PARA MICROORGANISMOS ANAEROBIOS DE CUALQUIER MUESTRA', True, 0),
('906603', 'ANTIGENO CARCINOEMBRIONARIO (ACE-CEA)', True, 0),
('906606', 'ANTIGENO DE CANCER DE TUBO DIGESTIVO (CA 19-9)', True, 0),
('903838', 'GAMMA GLUTAMIL TRANSFERASA (GAMMA GT)', True, 0),
('905706', 'ALCOHOL ETILICO EN CUALQUIER MUESTRA', True, 0),
('901304', 'EXAMEN DIRECTO FRESCO DE CUALQUIER MUESTRA', True, 0),
('911018', 'HEMOCLASIFICACION GRUPO ABO, DIRECTA O GLOBULAR EN PLACA', True, 0),
('903844', 'GLUCOSA- CURVA DE TOLERANCIA (POR MUESTRA) (115)', True, 0),
('902002', 'AGREGACION PLAQUETARIA, CADA AGENTE', True, 0),
('902003', 'AGREGACION PLAQUETARIA, CURVA', True, 0),
('906835', 'INMUNOGLOBULINA E (IG E) TOTAL POR EIA', True, 0),
('906223', 'HEPATITIS B, ANTICUERPOS S (ANTI-HBS) *', True, 0),
('906602', 'ALFA FETOPROTEINA (AFP) SERICA', True, 0),
('906605', 'ANTIGENO DE CANCER DE OVARIO (CA 125)', True, 0),
('906423', 'FOSFOLIPIDOS, ANTICUERPOS IG M POR EIA (117)', True, 0),
('906408', 'CARDIOLIPINA, ANTICUERPOS IG G POR EIA', True, 0),
('906482', 'BETA 2 GLICOPROTEINA I IG M SEMIAUTOMATIZADO O AUTOMATIZADO', True, 0),
('906409', 'CARDIOLIPINA, ANTICUERPOS IG M POR EIA', True, 0),
('906481', 'BETA 2 GLICOPROTEINA I IG G SEMIAUTOMATIZADO O AUTOMATIZADO', True, 0),
('906422', 'FOSFOLIPIDOS, ANTICUERPOS IG G POR EIA (117)', True, 0),
('903847', 'LIPASA', True, 0),
('901206', 'COPROCULTIVO', True, 0),
('908859', 'IDENTIFICACION SIMULTANEA DE MULTIPLES PATOGENOS POR PRUEBAS', True, 0),
('901002', 'ANTIBIOGRAMA (MIC) METODO AUTOMATICO', True, 0),
('907015', 'ESTEATOCRITO ACIDO', True, 0),
('901321', 'STREPTOCOCCUS BETA HEMOLITICO GRUPO A (PRUEBA RAPIDA)', True, 0),
('901305', 'EXAMEN DIRECTO PARA HONGOS (KOH)', True, 0),
('904904', 'HORMONA ESTIMULANTE DEL TIROIDES (TSH) ULTRASENSIBLE', True, 0),
('901202', 'BORDETELLA PERTUSIS, CULTIVO', True, 0),
('903849', 'LIQUIDO ASCITICO (EXAMEN FISICO Y CITOQUIMICO)', True, 0),
('906220', 'HEPATITIS B, ANTICUERPOS CENTRAL IG M (ANTI-CORE HBC-M)', True, 0),
('903850', 'LIQUIDO CEFALORRAQUIDEO (LCR- EXAMEN FISICO Y CITOQUIMICO CO', True, 0),
('901109', 'COLORACION TINTA CHINA Y LECTURA', True, 0),
('906221', 'HEPATITIS B ANTICUERPOS CENTRAL TOTALES', True, 0),
('902036', 'PROTEINA S DE LA COAGULACION', True, 0),
('903853', 'LIQUIDO SINOVIAL (EXAMEN FISICO Y CITOQUIMICO)', True, 0),
('903857', 'NITROGENO UREICO (BUN) EN ORINA DE 24 H', True, 0),
('908825', 'MYCOBACTERIUM TUBERCULOSIS IDENTIFICACION PCR', True, 0),
('906318', 'HEPATITIS B, ANTIGENO E (AG HBE)', True, 0),
('903065', 'PRO PEPTIDO ATRIAL NATRIURETICO [PRO-BNP] (PEPTIDO CEREBRAL', True, 0),
('901230', 'MYCOBACTERIUM TUBERCULOSIS, CULTIVO', True, 0),
('906337', 'HISTOPLASMA CAPSULATUM ANTIGENO SEMIAUTOMATIZADO O AUTOMATIZ', True, 0),
('906126', 'TOXOPLASMA GONDII, ANTICUERPOS IG A', True, 0),
('906012', 'BRUCELLA, PRUEBA DE BANQ EN PLACA', True, 0),
('906417', 'DNA N, ANTICUERPOS POR INMUNOFLUORESCENCIA', True, 0),
('911015', 'HEMOCLASIFICACION FACTOR RH [FACTOR D] POR MICROTECNICA', True, 0),
('898243', 'ESTUDIO DE COLORACION INMUNOHISTOQUIMICA EN ESPECIMEN CON RE', True, 0),
('903406', 'ALFA 1 ANTITRIPSINA POR NEFELOMETRIA', True, 0),
('903812', 'CAPACIDAD DE COMBINACION DEL HIERRO (TIBC)', True, 0),
('903062', 'MEDICION DE GASES EN SANGRE VENOSA', True, 0),
('904922', 'TIROXINA TOTAL (T4)', True, 0),
('904925', 'TRIYODOTIRONINA TOTAL (T3)', True, 0),
('903865', 'SODIO EN ORINA DE 24 HORAS', True, 0),
('902215', 'HEMOPARASITOS- EXTENDIDO', True, 0),
('906712', 'LINFOCITOS T CD3 POR CITOMETRIA DE FLUJO', True, 0),
('905504', 'METOTREXATO SEMIAUTOMATIZADO O AUTOMATIZADO', True, 0),
('903802', 'ACIDO URICO EN ORINA DE 24 H', True, 0),
('903836', 'FOSFORO EN ORINA DE 24 HORAS', True, 0),
('903427', 'HEMOGLOBINA GLICOSILADA POR CROMATOGRAFIA DE COLUMNA', True, 0),
('904108', 'PROLACTINA (BASAL)', True, 0),
('908807', 'HEPATITIS C CARGA VIRAL', True, 0),
('903826', 'CUERPOS CETONICOS O CETONAS EN ORINA (114)', True, 0),
('903823', 'CREATININA DEPURACION', True, 0),
('906829', 'INMUNOGLOBULINA G (IGG) CUANTITATIVA', True, 0),
('906832', 'INMUNOGLOBULINA M (IGM) CUANTITATIVA', True, 0),
('908337', 'RELACION LACTATO/PIRUVATO', True, 0),
('906414', 'CITOPLASMA DE NEUTROFILOS, ANTICUERPOS TOTALES (C-ANCA O P-A', True, 0),
('902205', 'ERITROSEDIMENTACION (VELOCIDAD SEDIMENTACION GLOBULAR - VSG', True, 0),
('903861', 'PROTEINAS DIFERENCIADAS', True, 0),
('906247', 'VARICELA ZOSTER, ANTICUERPOS IG G', True, 0),
('906906', 'COMPLEMENTO SERICO C3 CUANTITATIVO AUTOMATIZADO', True, 0),
('906908', 'COMPLEMENTO SERICO C4 CUANTITATIVO AUTOMATIZADO', True, 0),
('903026', 'MICROALBUMINURIA (PARCIAL)', True, 0),
('904602', 'TESTOSTERONA TOTAL', True, 0),
('904809', 'DEHIDROEPIANDROSTERONA SULFATO (EPIANDROSTERONA -DHEA-SO4)', True, 0),
('906039', 'TREPONEMA PALLIDUM, ANTICUERPOS (FTA-ABS O TPHA-PRUEBA TREPO', True, 0),
('911007', 'COOMBS DIRECTO FRACCIONADO MONOESPECIFICO (INMUNOGLOBULINAS', True, 0),
('906460', 'TIROIDEOS MICROSOMALES, ANTICUERPOS POR IHA', True, 0),
('902018', 'FACTOR VIII DE LA COAGULACION', True, 0),
('902005', 'ANTICOAGULANTE LUPICO- PRUEBA CONFIRMATORIA CON VENENO DE VI', True, 0),
('906231', 'HERPES II, ANTICUERPOS IG M', True, 0),
('906230', 'HERPES II, ANTICUERPOS IG G', True, 0),
('906229', 'HERPES I, ANTICUERPOS IG M', True, 0),
('906228', 'HERPES I, ANTICUERPOS IG G', True, 0),
('905707', 'ALCOHOL METILICO - FORMALDEHIDO', True, 0),
('906324', 'PARAINFLUENZA VIRUS ANTIGENO', True, 0),
('904924', 'TRIYODOTIRONINA LIBRE (T3L)', True, 0),
('903852', 'LIQUIDO PLEURAL (EXAMEN FISICO Y CITOQUIMICO)', True, 0),
('906493', 'N-METIL ASPARTATO RECEPTOR ANTICUERPOS SEMIAUTOMATIZADO O AU', True, 0),
('903707', 'VITAMINA D True,25 DIHIDROXI', True, 0),
('906826', 'INMUNOGLOBULINA A (IGA) CUANTITATIVA POR IDR', True, 0),
('908407', 'CARIOTIPO CON BANDEO RT EN CUALQUIER TIPO DE MUESTRA', True, 0),
('906720', 'LINFOCITOS T CD8 POR CITOMETRIA DE FLUJO', True, 0),
('906711', 'LINFOCITOS B, CUANTIFICACION (TOTALES CD19 Y MADUROS CD20) P', True, 0),
('906833', 'INMUNOGLOBULINA D (IG D) DOSIFICACION', True, 0),
('902026', 'HEPARINA, DOSIFICACION POR CROMOGENOS (ANTI FACTOR X ACTIVAD', True, 0),
('906035', 'MYCOPLASMA PNEUMONIAE, ANTICUERPOS IG M', True, 0),
('903402', 'ALDOLASA', True, 0),
('906025', 'HELICOBACTER PYLORI, ANTICUERPOS TOTALES', True, 0),
('906418', 'DNA N, ANTICUERPOS POR IFI', True, 0),
('903834', 'FOSFATASA ALCALINA ESPECIFICA DE HUESO', True, 0),
('906834', 'INMUNOGLOBULINA E (IG E) ESPECIFICA (DOSIFICACION CADA ALERG', True, 0),
('903401', 'ADENOSIN DEAMINASA (ADA)', True, 0),
('903424', 'DESHIDROGENASA HIDROXIBUTIRICA (HBDH)', True, 0),
('902010', 'DILUCIONES DE TIEMPO DE PROTROMBINA (PT)', True, 0),
('902007', 'ANTITROMBINA III', True, 0),
('903851', 'LIQUIDO PERITONEAL (EXAMEN FISICO Y CITOQUIMICO)', True, 0),
('906812', 'ELECTROFORESIS DE PROTEINAS EN CUALQUIER LIQUIDO INCLUIDO SU', True, 0),
('906801', 'BETA 2 GLICOPROTEINA', True, 0),
('906314', 'CRYPTOCOCCUS NEOFORMANS ANTIGENO', True, 0),
('906478', 'TRANSGLUTAMINASA ANTICUERPOS IG G SEMIAUTOMATIZADO O AUTOMAT', True, 0),
('906477', 'TRANSGLUTAMINASA ANTICUERPOS IG A SEMIAUTOMATIZADO O AUTOMAT', True, 0),
('903009', 'CATECOLAMINAS TOTALES EN ORINA DE 24 H', True, 0),
('904504', 'ESTRIOL', True, 0),
('903021', 'HAPTOGLOBINA POR NEFELOMETRIA', True, 0),
('903033', 'OSMOLARIDAD EN ORINA', True, 0),
('905313', 'LITIO EN SANGRE POR ABSORCION ATOMICA', True, 0),
('903028', 'MICROALBUMINURIA POR RIA', True, 0),
('906828', 'INMUNOGLOBULINA G (IGG) CUANTITATIVA POR IDR', True, 0),
('905301', 'ANFETAMINAS Y METANFETAMINAS CUANTITATIVAS AUTOMATIZADO', True, 0),
('906809', 'ELECTROFORESIS DE HEMOGLOBINA', True, 0),
('902109', 'GLUCOSA 6 FOSFATO DESHIDROGENASA, CUANTITATIVA', True, 0),
('901216', 'CULTIVO PARA MICROORGANISMOS ANAEROBIOS EN MEDULA OSEA', True, 0),
('903031', 'MIOGLOBINA EN ORINA', True, 0);

CREATE TABLE IF NOT EXISTS t013_queues(
    f013_id             INTEGER         PRIMARY KEY AUTOINCREMENT,
    f013_f008_id        INTEGER         NOT NULL,
    f013_create_at      DATETIME        DEFAULT (datetime('now', 'localtime')),
    f013_control_id     VARCHAR(250)    NOT NULL,
    f013_content_type   VARCHAR(50 )    DEFAULT 'text/hl7',
    f013_content        TEXT            NOT NULL,
    f013_indicted       BOOLEAN         DEFAULT FALSE,
    f013_indicted_at    DATETIME        DEFAULT NULL,
    f013_response       TEXT            DEFAULT NULL,
    FOREIGN KEY (f013_f008_id)
        REFERENCES t008_orders(f008_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);



